### ISSUE TITLE
unpaid era 6,513

### ISSUE THREAD

**Issue by hitchhooker** [paradox-tt/CrunchPayees#44]
ESSZefozpZYVLbLF1vaGtabthQYg8PVXiTytVm6YiiwAnee
DKKax6uZkiNPfd2ATd8cJhyi3c1KZD24VDdoWG9CfTmwgSp

noticed that I have my kusama wallets with unpaid era 5-6 eras back.

**Comment by paradox-tt** [comment]
Hey Hitch,

We're having some issues with the payout bot since the runtime upgrade.  We'll be back in fighting action very soon.

**Comment by paradox-tt** [comment]
I'm pleased to let you know that the era was paid out and we're back in fighting action.  Polkadot.JS has a bug that needs fixing and is displaying already paid out staking rewards.  I'm sure you're aware of this but I thought I'd mention it in the event others have similar concerns.
